# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20072dcf9f459bf91599eec6cc7e2c68f62820376e5f4ff61156bb412a636256de7874677ad117c009ba87c78eb21f21ff4b614d4e3867e9f67cf9968766847f

test:
  secret_key_base: e17f0f767daa872c2bfba351873b138b18f82cf40a2d9243f7136d9f73be49316857e2d0486f99342bf3356a5a498afd0966697708cd67a1b787ecb5fc8f57ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
